train_loss = 0.022096099331974983
train_accuracy = 0.8666658997535706
val_loss = 1.148947834968567
val_accuracy = 0.6687209010124207
val_f1 = 0.6702646239554317
val_macro_f1 = 0.6556296944618225
test_accuracy = 0.25550293922424316
test_f1 = 0.2555029256060184
test_macro_f1 = 0.25725477933883667
best_checkpoint = "/scratch/rra80/emotion-detection/runs/20251119-012955-2-gpu-run-full/checkpoints/epoch_0028"
best_epoch = 28

[history]
train_loss = [
    0.13252146542072296,
    0.12430192530155182,
    0.11206528544425964,
    0.102910615503788,
    0.09646447747945786,
    0.09158453345298767,
    0.08614389598369598,
    0.08225896954536438,
    0.07979333400726318,
    0.0767328292131424,
    0.07465749233961105,
    0.07306092977523804,
    0.07074154913425446,
    0.06866179406642914,
    0.06637867540121078,
    0.06596337258815765,
    0.06463086605072021,
    0.06217903643846512,
    0.060317136347293854,
    0.059003107249736786,
    0.05735881254076958,
    0.055393561720848083,
    0.0544322244822979,
    0.05241028591990471,
    0.05010898783802986,
    0.04778043180704117,
    0.04552171006798744,
    0.04423331841826439,
    0.04128555953502655,
    0.04009603336453438,
    0.03804406151175499,
    0.036000557243824005,
    0.03415786102414131,
    0.03151208534836769,
    0.029254304245114326,
    0.026308951899409294,
    0.024162806570529938,
    0.022096099331974983,
]
train_accuracy = [
    0.17332303524017334,
    0.24779441952705383,
    0.34952154755592346,
    0.40870749950408936,
    0.44690069556236267,
    0.46947383880615234,
    0.5059301257133484,
    0.5194985866546631,
    0.538996160030365,
    0.5525056719779968,
    0.5652587413787842,
    0.5720521807670593,
    0.5837624073028564,
    0.5903759598731995,
    0.6071193814277649,
    0.6071378588676453,
    0.6181671619415283,
    0.6289779543876648,
    0.6387965679168701,
    0.6445391178131104,
    0.6540599465370178,
    0.6674318909645081,
    0.6755704879760742,
    0.6808456182479858,
    0.6986329555511475,
    0.7077320218086243,
    0.7161345481872559,
    0.7306298017501831,
    0.7478774189949036,
    0.7540354132652283,
    0.7635244131088257,
    0.783428966999054,
    0.7926841974258423,
    0.8068209886550903,
    0.8239912986755371,
    0.8416696786880493,
    0.8555727005004883,
    0.8666658997535706,
]
val_loss = [
    1.9221020936965942,
    1.6562600135803223,
    1.69192636013031,
    1.4037227630615234,
    1.443650484085083,
    1.273627519607544,
    1.25905442237854,
    1.2572541236877441,
    1.1460835933685303,
    1.150413155555725,
    1.1110416650772095,
    1.09114408493042,
    1.1624176502227783,
    1.0727794170379639,
    1.099096655845642,
    1.067416787147522,
    1.0680745840072632,
    1.0165646076202393,
    1.0124595165252686,
    1.0034304857254028,
    1.0160943269729614,
    0.9815425872802734,
    1.017274022102356,
    0.9969242811203003,
    0.9854385852813721,
    0.9673675298690796,
    0.98566073179245,
    0.963775634765625,
    0.9823293685913086,
    1.0019530057907104,
    1.0039126873016357,
    1.009393572807312,
    1.0106629133224487,
    1.0443884134292603,
    1.0518524646759033,
    1.0888174772262573,
    1.1189262866973877,
    1.148947834968567,
]
val_accuracy = [
    0.18997476994991302,
    0.35874417424201965,
    0.34544837474823,
    0.46321815252304077,
    0.4419157803058624,
    0.5071331858634949,
    0.5100446343421936,
    0.5204289555549622,
    0.5636646151542664,
    0.5664305090904236,
    0.578125,
    0.5855492949485779,
    0.5627911686897278,
    0.6074825525283813,
    0.5896254181861877,
    0.5974864363670349,
    0.5993303656578064,
    0.6166052222251892,
    0.6082103848457336,
    0.6180609464645386,
    0.6193711161613464,
    0.6259219646453857,
    0.6270865797996521,
    0.634171187877655,
    0.6349961161613464,
    0.6491653919219971,
    0.6431968212127686,
    0.6495050191879272,
    0.6583365797996521,
    0.6510578393936157,
    0.6518827676773071,
    0.6509608030319214,
    0.6567352414131165,
    0.6552309989929199,
    0.6595497131347656,
    0.6604716777801514,
    0.6686238646507263,
    0.6687209010124207,
]
val_f1 = [
    0.19115598885793872,
    0.35967966573816157,
    0.3447075208913649,
    0.46274373259052926,
    0.4435933147632312,
    0.5073119777158774,
    0.5125348189415042,
    0.5222841225626741,
    0.5661559888579387,
    0.5703342618384402,
    0.58008356545961,
    0.5863509749303621,
    0.5661559888579387,
    0.6079387186629527,
    0.5905292479108635,
    0.5999303621169917,
    0.5995821727019499,
    0.6159470752089137,
    0.6100278551532033,
    0.620125348189415,
    0.620125348189415,
    0.6295264623955432,
    0.6284818941504178,
    0.6375348189415042,
    0.6361420612813371,
    0.6511142061281338,
    0.645891364902507,
    0.6514623955431755,
    0.6605153203342619,
    0.6521587743732591,
    0.653899721448468,
    0.6525069637883009,
    0.6584261838440112,
    0.6559888579387186,
    0.6608635097493036,
    0.6622562674094707,
    0.6706128133704735,
    0.6702646239554317,
]
val_macro_f1 = [
    0.18042150139808655,
    0.29669690132141113,
    0.2829788327217102,
    0.4070098400115967,
    0.40466123819351196,
    0.44147977232933044,
    0.4590950012207031,
    0.4589725434780121,
    0.5061489343643188,
    0.513700544834137,
    0.5431538820266724,
    0.5418254733085632,
    0.5064622163772583,
    0.575251042842865,
    0.5348418951034546,
    0.555848240852356,
    0.5489364862442017,
    0.5715956091880798,
    0.5571096539497375,
    0.5741265416145325,
    0.5809678435325623,
    0.5926762819290161,
    0.5870657563209534,
    0.5937233567237854,
    0.6043296456336975,
    0.6100345253944397,
    0.614771842956543,
    0.626096248626709,
    0.6399106979370117,
    0.6342671513557434,
    0.6377154588699341,
    0.627042293548584,
    0.6315786242485046,
    0.6321387887001038,
    0.6420537233352661,
    0.6491270661354065,
    0.6597986817359924,
    0.6556296944618225,
]
