train_loss = 0.02660846896469593
train_accuracy = 0.8412509560585022
val_loss = 1.1339774131774902
val_accuracy = 0.6490683555603027
val_f1 = 0.6514623955431755
val_macro_f1 = 0.6330496668815613
test_accuracy = 0.25842854380607605
test_f1 = 0.25842853162440793
test_macro_f1 = 0.25079402327537537
best_checkpoint = "/scratch/rra80/emotion-detection/runs/20251119-014724-2-gpu-run-full/checkpoints/epoch_0026"
best_epoch = 26

[history]
train_loss = [
    0.1323765218257904,
    0.1246490553021431,
    0.11295867711305618,
    0.10335799306631088,
    0.0969671830534935,
    0.09216370433568954,
    0.08656724542379379,
    0.08285123854875565,
    0.08094342797994614,
    0.07766468077898026,
    0.07536272704601288,
    0.07333990186452866,
    0.07046880573034286,
    0.0693318322300911,
    0.06696160137653351,
    0.06553280353546143,
    0.06481897085905075,
    0.06345108896493912,
    0.06018367409706116,
    0.059526365250349045,
    0.05789877846837044,
    0.05536879226565361,
    0.053740791976451874,
    0.05236983299255371,
    0.05056951567530632,
    0.04908840358257294,
    0.04589170962572098,
    0.04396883770823479,
    0.042211588472127914,
    0.04065760597586632,
    0.037892889231443405,
    0.035702720284461975,
    0.03407496586441994,
    0.03104032389819622,
    0.029164554551243782,
    0.02660846896469593,
]
train_accuracy = [
    0.17770367860794067,
    0.24347445368766785,
    0.3481561839580536,
    0.4026826024055481,
    0.44563788175582886,
    0.4672306478023529,
    0.5023635029792786,
    0.5170350670814514,
    0.5326146483421326,
    0.5491089820861816,
    0.5612683892250061,
    0.5751898884773254,
    0.5857114791870117,
    0.5865857601165771,
    0.5994094014167786,
    0.6127004027366638,
    0.6157018542289734,
    0.6250078082084656,
    0.6411018371582031,
    0.6433517932891846,
    0.6528947949409485,
    0.6680808663368225,
    0.6779094338417053,
    0.6836639642715454,
    0.6953319907188416,
    0.7031044363975525,
    0.7182482481002808,
    0.7339240312576294,
    0.7447513937950134,
    0.751874566078186,
    0.7684798836708069,
    0.782618522644043,
    0.7960372567176819,
    0.8121987581253052,
    0.824036717414856,
    0.8412509560585022,
]
val_loss = [
    1.9180047512054443,
    1.6793313026428223,
    1.6947681903839111,
    1.4276924133300781,
    1.4038493633270264,
    1.270946741104126,
    1.2681865692138672,
    1.2659082412719727,
    1.1857762336730957,
    1.1823536157608032,
    1.1331459283828735,
    1.0953385829925537,
    1.1645495891571045,
    1.0981321334838867,
    1.1161901950836182,
    1.0867878198623657,
    1.07277512550354,
    1.0267573595046997,
    1.0532712936401367,
    1.0284161567687988,
    1.0331673622131348,
    0.9895945191383362,
    1.0251575708389282,
    0.987850546836853,
    0.9945366978645325,
    0.9768993854522705,
    1.0144480466842651,
    0.9846736192703247,
    1.0025213956832886,
    1.0275510549545288,
    1.0135393142700195,
    1.0332450866699219,
    1.0495179891586304,
    1.09040367603302,
    1.116944670677185,
    1.1339774131774902,
]
val_accuracy = [
    0.18982918560504913,
    0.3572884500026703,
    0.33836376667022705,
    0.44468167424201965,
    0.4539984464645386,
    0.5077154636383057,
    0.510869562625885,
    0.5207686424255371,
    0.5403726696968079,
    0.5588606595993042,
    0.5694875717163086,
    0.5902076959609985,
    0.5627425909042358,
    0.5907900333404541,
    0.5802600979804993,
    0.5917119383811951,
    0.5953028202056885,
    0.6219914555549622,
    0.6138878464698792,
    0.6170904636383057,
    0.6160714030265808,
    0.6295128464698792,
    0.6286393404006958,
    0.6334918737411499,
    0.6370341777801514,
    0.6434879899024963,
    0.6172845959663391,
    0.6415955424308777,
    0.6486316323280334,
    0.6419351696968079,
    0.6475155353546143,
    0.6535811424255371,
    0.6476125717163086,
    0.6379561424255371,
    0.6421293020248413,
    0.6490683555603027,
]
val_f1 = [
    0.18697771587743733,
    0.35863509749303624,
    0.3387883008356546,
    0.4477715877437326,
    0.45508356545961004,
    0.5114902506963789,
    0.5111420612813371,
    0.5226323119777159,
    0.5431754874651811,
    0.5598885793871866,
    0.5703342618384402,
    0.5915738161559888,
    0.5647632311977716,
    0.5926183844011143,
    0.5818245125348189,
    0.5940111420612814,
    0.5967966573816156,
    0.6232590529247911,
    0.6162952646239555,
    0.6204735376044568,
    0.6162952646239555,
    0.6323119777158774,
    0.6323119777158774,
    0.6368384401114207,
    0.6382311977715878,
    0.6448467966573816,
    0.6197771587743732,
    0.6438022284122563,
    0.6514623955431755,
    0.6441504178272981,
    0.650766016713092,
    0.6556406685236769,
    0.6504178272980501,
    0.6396239554317549,
    0.6434540389972145,
    0.6514623955431755,
]
val_macro_f1 = [
    0.17860789597034454,
    0.3010944724082947,
    0.2885429561138153,
    0.40322059392929077,
    0.4094000458717346,
    0.44043269753456116,
    0.4562424123287201,
    0.45474129915237427,
    0.4800516963005066,
    0.49661654233932495,
    0.5301253199577332,
    0.5485482811927795,
    0.5044201016426086,
    0.5477607250213623,
    0.518632709980011,
    0.5465887784957886,
    0.5479593873023987,
    0.5688201189041138,
    0.5603243112564087,
    0.5741050839424133,
    0.5822192430496216,
    0.6067323088645935,
    0.5932767987251282,
    0.6058147549629211,
    0.6034683585166931,
    0.6103009581565857,
    0.589174747467041,
    0.6122797131538391,
    0.625311017036438,
    0.6305502653121948,
    0.6296753287315369,
    0.6334410309791565,
    0.6301866173744202,
    0.616221010684967,
    0.6232468485832214,
    0.6330496668815613,
]
