train_loss = 0.026112934574484825
train_accuracy = 0.8428938388824463
val_loss = 1.0931013822555542
val_accuracy = 0.6499418020248413
val_f1 = 0.6545961002785515
val_macro_f1 = 0.6421193480491638
test_accuracy = 0.2628866136074066
test_f1 = 0.26288659793814434
test_macro_f1 = 0.25799256563186646
best_checkpoint = "/home/vss54/emotion/emotion-detection/runs/20251121-120053-2gpu-insightface-fer2013/checkpoints/epoch_0026"
best_epoch = 26

[history]
train_loss = [
    0.13242954015731812,
    0.12461381405591965,
    0.11268877983093262,
    0.10304976999759674,
    0.09634412825107574,
    0.09126590937376022,
    0.08627502620220184,
    0.08228813856840134,
    0.07986185699701309,
    0.07724286615848541,
    0.07500693947076797,
    0.07299064099788666,
    0.07050937414169312,
    0.06952796131372452,
    0.06565229594707489,
    0.0651787593960762,
    0.06423451751470566,
    0.062173616141080856,
    0.06060022488236427,
    0.058234233409166336,
    0.05655653029680252,
    0.055334530770778656,
    0.05442288890480995,
    0.05212533473968506,
    0.05108226090669632,
    0.04787302389740944,
    0.04583929106593132,
    0.0445372648537159,
    0.04114421084523201,
    0.04081261530518532,
    0.03774292394518852,
    0.03447823226451874,
    0.033545587211847305,
    0.030546942725777626,
    0.028558529913425446,
    0.026112934574484825,
]
train_accuracy = [
    0.17602714896202087,
    0.24089166522026062,
    0.346950501203537,
    0.39937493205070496,
    0.4494163990020752,
    0.47108474373817444,
    0.5042585730552673,
    0.5205225944519043,
    0.5381065607070923,
    0.5495074391365051,
    0.5630339980125427,
    0.5726305246353149,
    0.5849815607070923,
    0.587579607963562,
    0.6127053499221802,
    0.6131375432014465,
    0.6154850125312805,
    0.6318970322608948,
    0.637563943862915,
    0.6489530205726624,
    0.6597773432731628,
    0.6692663431167603,
    0.6705039739608765,
    0.683332622051239,
    0.6936270594596863,
    0.7090132832527161,
    0.7208480834960938,
    0.7277930378913879,
    0.7497338652610779,
    0.7517063021659851,
    0.7693173289299011,
    0.7889596223831177,
    0.7962558269500732,
    0.8128377795219421,
    0.8263001441955566,
    0.8428938388824463,
]
val_loss = [
    1.9137436151504517,
    1.6859838962554932,
    1.6720894575119019,
    1.4195141792297363,
    1.3921051025390625,
    1.266253113746643,
    1.2575874328613281,
    1.2525253295898438,
    1.1760023832321167,
    1.129677653312683,
    1.103548526763916,
    1.097495436668396,
    1.2132301330566406,
    1.0701056718826294,
    1.10030198097229,
    1.0584280490875244,
    1.0521537065505981,
    1.0318118333816528,
    1.0113447904586792,
    1.0295275449752808,
    1.0052945613861084,
    1.0105260610580444,
    1.0177521705627441,
    0.9756039381027222,
    0.9885867834091187,
    0.9592001438140869,
    0.9925566911697388,
    0.9681188464164734,
    0.9957090616226196,
    1.0067123174667358,
    1.0010652542114258,
    1.0398085117340088,
    1.0362706184387207,
    1.0496459007263184,
    1.0697696208953857,
    1.0931013822555542,
]
val_accuracy = [
    0.18643245100975037,
    0.34447789192199707,
    0.3430221378803253,
    0.4580260217189789,
    0.4491944909095764,
    0.5168866515159607,
    0.5106754899024963,
    0.5394992232322693,
    0.5571622848510742,
    0.5721564888954163,
    0.5821040272712708,
    0.5864712595939636,
    0.5595885515213013,
    0.609714686870575,
    0.582880437374115,
    0.6129658222198486,
    0.598505437374115,
    0.6154406070709229,
    0.6218944191932678,
    0.6120923757553101,
    0.6287849545478821,
    0.6240295171737671,
    0.6272806525230408,
    0.6433908939361572,
    0.6334433555603027,
    0.6475155353546143,
    0.6413528919219971,
    0.6567352414131165,
    0.6457686424255371,
    0.6513490080833435,
    0.6524651050567627,
    0.6480493545532227,
    0.649796187877655,
    0.6480007767677307,
    0.649796187877655,
    0.6499418020248413,
]
val_f1 = [
    0.18662952646239556,
    0.3450557103064067,
    0.34401114206128136,
    0.4610027855153203,
    0.451949860724234,
    0.5177576601671309,
    0.5118384401114207,
    0.540041782729805,
    0.5581476323119777,
    0.5748607242339833,
    0.5846100278551533,
    0.5877437325905293,
    0.5619777158774373,
    0.6093314763231198,
    0.5818245125348189,
    0.6149025069637883,
    0.600974930362117,
    0.616991643454039,
    0.6236072423398329,
    0.6149025069637883,
    0.6302228412256268,
    0.6253481894150418,
    0.6309192200557103,
    0.6451949860724234,
    0.6354456824512534,
    0.650766016713092,
    0.6431058495821727,
    0.6584261838440112,
    0.6476323119777159,
    0.6542479108635098,
    0.6549442896935933,
    0.6504178272980501,
    0.6535515320334262,
    0.649025069637883,
    0.6504178272980501,
    0.6545961002785515,
]
val_macro_f1 = [
    0.17872345447540283,
    0.28664058446884155,
    0.2905939221382141,
    0.40618425607681274,
    0.4028328061103821,
    0.4428180754184723,
    0.4552021622657776,
    0.47983673214912415,
    0.4965166449546814,
    0.5160862803459167,
    0.5525482296943665,
    0.5434909462928772,
    0.5035684704780579,
    0.5621864199638367,
    0.52121502161026,
    0.5684898495674133,
    0.5548847317695618,
    0.5766611695289612,
    0.5760785341262817,
    0.5648266077041626,
    0.5889415740966797,
    0.5909074544906616,
    0.5905529260635376,
    0.6202162504196167,
    0.5946019291877747,
    0.6195055246353149,
    0.6204232573509216,
    0.633263885974884,
    0.6258164644241333,
    0.6386843919754028,
    0.6329546570777893,
    0.6275290250778198,
    0.637834906578064,
    0.6269961595535278,
    0.6299908757209778,
    0.6421193480491638,
]
