train_loss = 0.03132524713873863
train_accuracy = 0.8112435340881348
val_loss = 1.0562680959701538
val_accuracy = 0.6483404636383057
val_f1 = 0.6493732590529248
val_macro_f1 = 0.615631103515625
test_accuracy = 0.2691557705402374
test_f1 = 0.26915575369183614
test_macro_f1 = 0.2677789330482483
best_checkpoint = "/home/vss54/emotion/emotion-detection/runs/20251119-110026-2-gpu-run-full/checkpoints/epoch_0024"
best_epoch = 24

[history]
train_loss = [
    0.13232402503490448,
    0.12477628141641617,
    0.11246369779109955,
    0.10377774387598038,
    0.09641467034816742,
    0.09155401587486267,
    0.08611251413822174,
    0.08275865763425827,
    0.07987327873706818,
    0.0772140622138977,
    0.07522305101156235,
    0.0732799544930458,
    0.0706755593419075,
    0.06943318247795105,
    0.06660741567611694,
    0.06525315344333649,
    0.06427110731601715,
    0.06301305443048477,
    0.06025994196534157,
    0.05918504670262337,
    0.05730944871902466,
    0.05566313490271568,
    0.053983256220817566,
    0.051619112491607666,
    0.05014197528362274,
    0.049842093139886856,
    0.04551555961370468,
    0.04441903159022331,
    0.04179931432008743,
    0.04025571420788765,
    0.03745598718523979,
    0.03543321043252945,
    0.03400762379169464,
    0.03132524713873863,
]
train_accuracy = [
    0.17677369713783264,
    0.2419745922088623,
    0.34425488114356995,
    0.4019140303134918,
    0.44759508967399597,
    0.47519785165786743,
    0.5037288665771484,
    0.5231980085372925,
    0.539530873298645,
    0.5479487180709839,
    0.564167320728302,
    0.5725868940353394,
    0.5847427845001221,
    0.5877662301063538,
    0.6037982702255249,
    0.6113854050636292,
    0.6195140480995178,
    0.6259225606918335,
    0.6391631960868835,
    0.6447391510009766,
    0.6565537452697754,
    0.6626527905464172,
    0.6735256314277649,
    0.6877617835998535,
    0.6971195936203003,
    0.7001312971115112,
    0.7181456685066223,
    0.7313327193260193,
    0.7443898916244507,
    0.7546457052230835,
    0.7710594534873962,
    0.7842730283737183,
    0.7947860956192017,
    0.8112435340881348,
]
val_loss = [
    1.9145888090133667,
    1.6721266508102417,
    1.6752334833145142,
    1.4247562885284424,
    1.4346351623535156,
    1.3109323978424072,
    1.2722917795181274,
    1.2718828916549683,
    1.1738619804382324,
    1.1641684770584106,
    1.1445568799972534,
    1.1098990440368652,
    1.2030481100082397,
    1.1034542322158813,
    1.098671555519104,
    1.0589029788970947,
    1.0576488971710205,
    1.0283088684082031,
    1.0186337232589722,
    1.046481728553772,
    1.0453860759735107,
    1.0220770835876465,
    1.0305997133255005,
    0.9739859104156494,
    1.006132960319519,
    0.9758493304252625,
    0.9984455108642578,
    0.9880944490432739,
    0.9945654273033142,
    1.017088770866394,
    1.0108774900436401,
    1.0334968566894531,
    1.0697013139724731,
    1.0562680959701538,
]
val_accuracy = [
    0.1877911388874054,
    0.354619562625885,
    0.3459821343421936,
    0.46394607424736023,
    0.4486607313156128,
    0.4955357313156128,
    0.509171187877655,
    0.5192643404006958,
    0.5569681525230408,
    0.5643439888954163,
    0.5608501434326172,
    0.5796778202056885,
    0.5510966777801514,
    0.5855492949485779,
    0.5789984464645386,
    0.5999612212181091,
    0.5919060707092285,
    0.6231560707092285,
    0.6224766969680786,
    0.6016595959663391,
    0.6130629181861877,
    0.620244562625885,
    0.6208754181861877,
    0.6427115797996521,
    0.6285908222198486,
    0.6392177939414978,
    0.6424204707145691,
    0.6450892686843872,
    0.6529017686843872,
    0.6478552222251892,
    0.6513490080833435,
    0.6504755616188049,
    0.6457201242446899,
    0.6483404636383057,
]
val_f1 = [
    0.18802228412256267,
    0.354108635097493,
    0.3474930362116992,
    0.4648328690807799,
    0.4491643454038997,
    0.4972144846796657,
    0.5125348189415042,
    0.5201949860724234,
    0.5588440111420613,
    0.5668523676880223,
    0.5637186629526463,
    0.5839136490250696,
    0.5532729805013927,
    0.5863509749303621,
    0.58008356545961,
    0.6020194986072424,
    0.5933147632311978,
    0.6253481894150418,
    0.6246518105849582,
    0.6037604456824512,
    0.6145543175487466,
    0.6232590529247911,
    0.6225626740947076,
    0.6444986072423399,
    0.6309192200557103,
    0.6413649025069638,
    0.6455431754874652,
    0.6469359331476323,
    0.6549442896935933,
    0.6479805013927576,
    0.6542479108635098,
    0.6511142061281338,
    0.6462395543175488,
    0.6493732590529248,
]
val_macro_f1 = [
    0.17580701410770416,
    0.2935176193714142,
    0.3001609146595001,
    0.41642528772354126,
    0.40575525164604187,
    0.4320205748081207,
    0.45876190066337585,
    0.4580407440662384,
    0.49762600660324097,
    0.5019649863243103,
    0.5198342204093933,
    0.5359026193618774,
    0.49254539608955383,
    0.5400801301002502,
    0.5256262421607971,
    0.5566131472587585,
    0.5439897179603577,
    0.5741913914680481,
    0.5791128277778625,
    0.5512615442276001,
    0.5786792635917664,
    0.5880669951438904,
    0.5838360786437988,
    0.6132289171218872,
    0.5936616659164429,
    0.610619843006134,
    0.6228150725364685,
    0.6195607781410217,
    0.6336771845817566,
    0.6221503019332886,
    0.6349726915359497,
    0.6306887269020081,
    0.6263840794563293,
    0.615631103515625,
]
