train_loss = 0.11700732260942459
train_accuracy = 0.3161699175834656
val_loss = 1.5217241048812866
val_accuracy = 0.4234277904033661
val_f1 = 0.42374651810584957
val_macro_f1 = 0.3558981716632843
test_accuracy = 0.2248537242412567
test_f1 = 0.22485371969908052
test_macro_f1 = 0.18526040017604828
best_checkpoint = "/scratch/rra80/emotion-detection/runs/20251119-005506-gh-full/checkpoints/epoch_0002"
best_epoch = 2

[history]
train_loss = [
    0.13134393095970154,
    0.11700732260942459,
]
train_accuracy = [
    0.18590791523456573,
    0.3161699175834656,
]
val_loss = [
    1.8525389432907104,
    1.5217241048812866,
]
val_accuracy = [
    0.24786491692066193,
    0.4234277904033661,
]
val_f1 = [
    0.24825905292479108,
    0.42374651810584957,
]
val_macro_f1 = [
    0.21230915188789368,
    0.3558981716632843,
]
